module.exports = {
    // common
    CLEAR_ACTION: 'CLEAR_ACTION',
    STATUS: {
        FETCHING: '_FETCHING',
        SUCCESS: '_SUCCESS',
        FAIL: '_FAIL',
        HANDLE_DROP: '_HANDLE_DROP',
        ADD_NEW: '_ADD_NEW',
        SELECT: '_SELECT',
        UPDATE: '_UPDATE',
        DESELECT: '_DESELECT',
        RE_ORDER: '_REORDER'
    },
    IMAGES: "IMAGES",
    SELECTED_IMAGES: "SELECTED_IMAGES",
    ACKNOWLEDGE_ERROR: "ACKNOWLEDGE_ERROR",
    TRIGGER_ERROR: "TRIGGER_ERROR",
};