export const ResponseMessage = {
    UPDATE_SUCCESS: 'Successfully updated',
    INSERT_SUCCESS: 'Successfully inserted',
    DATABASE_ERROR: 'Database error',
    INVALID_PARAMTERS: 'Invalid parameters',
    NO_RECORD_FOUND_FOR_THE_PARAMTERS: 'No data found for the given paramter',
    INVALID_CREDS: 'Invalid login credentials',
    EMAIL_ALREADY_USED: 'The email address has already been registered for a different account',
    DATA_NOT_FOUND: 'Data not found',
    DATA_FOUND: 'Data found',
    DELETE_SUCCESS: 'Successfully deleted',
    PHOTO_SELECTION_SUCCESS: 'Successfully selected the photo',
    PHOTO_SELECTION_ERROR: 'You can not select same photo twice',
    PHOTO_SELECTION_VALIDATION: 'You can only select nine photos into a album',
    PHOTO_SELECTION_ORDERED_SUCCESS: 'Selected photo list successfully ordered',
    SIGNIN_SUCCESS: 'User has successfully sign-in',
    SIGNUP_SUCCESS: 'User has successfully sign-up',
}